# @package _global_
defaults:
  - /trainer: default
  - /loader: default
  - /dataset: imdb-lm
#  - /task: multiclass_classification
  - /optimizer: adamw
  - /scheduler: plateau

task:
   _name_: base
   loss: cross_entropy
   metrics:
     - accuracy_ignore_m100
   torchmetrics: null

train:
  monitor: val/accuracy_ignore_m100  # Needed for plateau scheduler
  mode: max

encoder: embedding

decoder:
  _name_: sequence
  mode: last
  use_lengths: false
