# @package _global_
defaults:
  - /trainer: default
  - /loader: default
  - /dataset: etth
#  - /task: regression
  - /optimizer: adamw
  - /scheduler: plateau

train:
  seed: 2222
#  interval: step # For cosine scheduler
  monitor: val/loss # Needed for plateau scheduler
  mode: min

task:
  _name_: base
  loss: mse
  metrics:
    - mse
    - mae
    - r2
  torchmetrics: null

encoder: linear
#encoder:
#  - linear
#  - _name_: time
#    timeenc: ${dataset.timeenc}

decoder:
  _name_: sequence
  mode: last

# This dataset is super prone to overfitting so we check validation more often
trainer:
  val_check_interval: 0.2
