# @package _global_
defaults:
  - /trainer: default
  - /optimizer: adamw
  - /scheduler: constant
  - /loader: torch
  - /dataset: pathfinder-segmentation

train:
  monitor: val/f1_macro  # Needed for plateau scheduler
  mode: max

task:
  _name_: base
  loss: class_weighted_cross_entropy
  metrics:
    - f1_macro
    - accuracy_balanced
  torchmetrics: null

encoder: linear

decoder:
  _name_: sequence
  mode: last

trainer:
  val_check_interval: 0.5
