defaults:
  - base
  - override layer: dlr

transposed: false # Actually faster than "true"
tie_dropout: False

#_name_: model
#prenorm: False
#transposed: True
#n_layers: 4
#d_model: 256
#residual: R
#pool:
#  _name_: sample
#  pool: 1
#  expand: 1
#norm: layer
#dropout: 0.0