_name_: parity

batch_size: 128
predict_token: 2
ignore_token: -1

train:
  predict_token: ${predict_token}
  ignore_token: ${ignore_token}
  batch_size: ${batch_size}
  min_length: 2
  max_length: 40
  length_spacing: 1

test:
  predict_token: ${predict_token}
  ignore_token: ${ignore_token}
  batch_size: ${batch_size}
  min_length: 41
  max_length: 400
  length_spacing: 20
