_name_: etth
size:
  - 384  # seq len
  - 96   # label len
  - 96   # pred len
features: 'S'
target: 'OT'
variant: 0
scale: True
inverse: False
timeenc: 0
eval_stamp: False
eval_mask: False
# freq: 'h' # Shouldn't touch
__l_max: ${eval:${.size.0}+${.size.2}}
