_name_: dlr
d_state: 1024               # use 4096 to model very long L
bidirectional: false
activation: gelu
postact: null
hyper_act: null
dropout: ${..dropout} # Same as null
dt_min: 0.0001
dt_max: 0.1
trainable:
    Lambda: true
    W: true
lr:
    Lambda: 0.0001
    Lambda_re: null
    W: 0.0001
max_kernel_length: null
kernel_type: dlr
Lambda_init: omega
W_scale: null    # default 1/d_state
wd: 0            # wt decay of W
pykeops: true
version: ''     # Lambda_imag_W_real
kernel_to_real: real
chunk_size: null  # chunk size in case of attention
attn_ff: 0        # expansion of FF layer at end of attn
l_max: ${oc.select:dataset.__l_max,1} # Grab dataset length if exists, otherwise set to 1 and kernel will automatically resize
verbose: false